### PR TITLE
fix(web): dashboard sessions page

### LINKED ISSUE #4856: [Bug]: Sessions section not working
### Affected component

unknown

### Severity

S2 - degraded behavior

### Current behavior

While navigating to the `sessions` section, i see the following error.
Probably that's because the `slice` method is invoked on the `id` filed, which is not returned by the api. The api is returning `session_id` instead

Image

### Expected behavior

I can correctly see the sessions section

### Steps to reproduce

```bash
Open the dashboard
Navigate to the sessions section
```

### Impact

_No response_

### Logs / stack traces

```text

```

### ZeroClaw version

0.6.5

### Rust version

_No response_

### Operating system

Docker

### Regression?

Yes, it worked before

### Pre-flight checks

- [x] I reproduced this on the latest master branch or latest release.
- [x] I redacted secrets, tokens, and personal data from all submitted content.

### PR DESCRIPTION
**Pull request by ilteoood**
## Summary

Describe this PR in 2-5 bullets:

- Base branch target (`master` for all contributions): master
- Problem: #4856, [#4918](https://github.com/zeroclaw-labs/zeroclaw/issues/4918)
- Why it matters: The section is not usable at all
- What changed: Fixed the session type definition, and removed what's not available anymore
- What did **not** change (scope boundary):

## Label Snapshot (required)

- Risk label (`risk: low|medium|high`): low
- Size label (`size: XS|S|M|L|XL`, auto-managed/read-only): xs
- Scope labels (`core|agent|channel|config|cron|daemon|doctor|gateway|health|heartbeat|integration|memory|observability|onboard|provider|runtime|security|service|skillforge|skills|tool|tunnel|docs|dependencies|ci|tests|scripts|dev`, comma-separated): dashboard
- Module labels (`<module>: <component>`, for example `channel: telegram`, `provider: kimi`, `tool: shell`): dashboard
- Contributor tier label (`trusted contributor|experienced contributor|principal contributor|distinguished contributor`, auto-managed/read-only; author merged PRs >=5/10/20/50): distinguished contributor
- If any auto-label is incorrect, note requested correction:

## Change Metadata

- Change type (`bug|feature|refactor|docs|security|chore`): bug
- Primary scope (`runtime|provider|channel|memory|security|ci|docs|multi`): dashboard

## Linked Issue

- Closes #4856
- Related #4856
- Depends on # (if stacked)
- Supersedes # (if replacing older PR)

## Supersede Attribution (required when `Supersedes #` is used)

- Superseded PRs + authors (`#<pr> by @<author>`, one per line):
- Integrated scope by source PR (what was materially carried forward):
- `Co-authored-by` trailers added for materially incorporated contributors? (`Yes/No`)
- If `No`, explain why (for example: inspiration-only, no direct code/design carry-over):
- Trailer format check (separate lines, no escaped `\n`): (`Pass/Fail`)

## Validation Evidence (required)

Commands and result summary:

```bash
cargo fmt --all -- --check
cargo clippy --all-targets -- -D warnings
cargo test
```

- Evidence provided (test/log/trace/screenshot/perf):
- If any command is intentionally skipped, explain why:

## Security Impact (required)

- New permissions/capabilities? (`Yes/No`)
- New external network calls? (`Yes/No`)
- Secrets/tokens handling changed? (`Yes/No`)
- File system access scope changed? (`Yes/No`)
- If any `Yes`, describe risk and mitigation:

## Privacy and Data Hygiene (required)

- Data-hygiene status (`pass|needs-follow-up`):
- Redaction/anonymization notes:
- Neutral wording confirmation (use ZeroClaw/project-native labels if identity-like wording is needed):

## Compatibility / Migration

- Backward compatible? (`Yes/No`)
- Config/env changes? (`Yes/No`)
- Migration needed? (`Yes/No`)
- If yes, exact upgrade steps:

## i18n Follow-Through (required when docs or user-facing wording changes)

- i18n follow-through triggered? (`Yes/No`)
- If `Yes`, locale navigation parity updated in `README*`, `docs/README*`, and `docs/SUMMARY.md` for supported locales (`en`, `zh-CN`, `ja`, `ru`, `fr`, `vi`)? (`Yes/No`)
- If `Yes`, localized runtime-contract docs updated where equivalents exist (minimum for `fr`/`vi`: `commands-reference`, `config-reference`, `troubleshooting`)? (`Yes/No/N.A.`)
- If `Yes`, Vietnamese canonical docs under `docs/i18n/vi/**` synced and compatibility shims under `docs/*.vi.md` validated? (`Yes/No/N.A.`)
- If any `No`/`N.A.`, link follow-up issue/PR and explain scope decision:

## Human Verification (required)

What was personally validated beyond CI:

- Verified scenarios:
- Edge cases checked:
- What was not verified:

## Side Effects / Blast Radius (required)

- Affected subsystems/workflows:
- Potential unintended effects:
- Guardrails/monitoring for early detection:

## Agent Collaboration Notes (recommended)

- Agent tools used (if any):
- Workflow/plan summary (if any):
- Verification focus:
- Confirmation: naming + architecture boundaries followed (`AGENTS.md` + `CONTRIBUTING.md`):

## Rollback Plan (required)

- Fast rollback command/path:
- Feature flags or config toggles (if any):
- Observable failure symptoms:

## Risks and Mitigations

List real risks in this PR (or write `None`).

- Risk:
- Mitigation:

### CODE REVIEW

**Comment by theonlyhennygod** [comment]
Hey @ilteoood, CI is failing on this PR with **2 failures**:

### 1. `Check (all features)` — missing file
```
error: couldn't read `src/hardware/../../firmware/pico/main.py`: No such file or directory (os error 2)
  --> src/hardware/uf2.rs:23:33
```
The file `firmware/pico/main.py` is missing from this branch. It's referenced via `include_bytes!` and the build can't compile without it.

### 2. `Security Audit` — vulnerable dependency (RUSTSEC-2026-0049)
```
Crate:    rustls-webpki
Version:  0.102.8
Title:    CRLs not considered authoritative by Distribution Point due to faulty matching logic
Solution: Upgrade to >=0.103.10
```

Both cascade into the **CI Required Gate** and **Security Required Gate** failures. Please fix and push an update. Thanks!

**Comment by ilteoood** [comment]
> Hey @ilteoood, CI is failing on this PR with **2 failures**:
> 
> ### 1. `Check (all features)` — missing file
> ```
> error: couldn't read `src/hardware/../../firmware/pico/main.py`: No such file or directory (os error 2)
>   --> src/hardware/uf2.rs:23:33
> ```
> 
> The file `firmware/pico/main.py` is missing from this branch. It's referenced via `include_bytes!` and the build can't compile without it.
> 
> ### 2. `Security Audit` — vulnerable dependency (RUSTSEC-2026-0049)
> ```
> Crate:    rustls-webpki
> Version:  0.102.8
> Title:    CRLs not considered authoritative by Distribution Point due to faulty matching logic
> Solution: Upgrade to >=0.103.10
> ```
> 
> Both cascade into the **CI Required Gate** and **Security Required Gate** failures. Please fix and push an update. Thanks!

Nothing to do on my side @theonlyhennygod, the repo contained those issues. Re aligning with main fixed them.

**Comment by JordanTheJet** [comment]
## 🤖 Agent Review — PR #5199

**Verdict: Needs author action**

This PR takes the right approach — aligning the TypeScript `Session` type to match the actual gateway API contract rather than fabricating fields client-side (as #5211 does). However, there are a few issues to address before this is merge-ready.

---

### 1. Bug: Duplicate `name` field in `src/gateway/api.rs` (Blocking)

The new line `"name": meta.name` at L1300 conflicts with the existing `if let Some(name) = meta.name` block at L1301-1303. This causes:

- **Double assignment** when `meta.name` is `Some(...)` — the key is set twice.
- **`null` emission** when `meta.name` is `None` — previously `name` was omitted from the JSON entirely, now it will be `"name": null`. The TypeScript type has `name?: string` (optional), so consumers checking `session.name !== undefined` will break.

**Fix:** Remove the `"name": meta.name` line from the `json!()` macro. The existing `if let` pattern already handles this correctly.

### 2. Incomplete i18n key cleanup (Blocking)

`dashboard.session_channel` and `dashboard.session_status` were removed from only 3 locales (zh-CN, en, tr). The remaining 28 locales still contain these dead keys. All locales should be cleaned up for parity per `docs-contract.md`.

### 3. Overlap with PR #5211

Both PRs fix #4918. This PR is the stronger approach (types should match the real API, not fabricate defaults), but the two should be coordinated. The unrelated Rust fixes in #5211 (clippy/rustfmt in `onboarding.rs`, mattermost test stabilization) are valid and could be cherry-picked into their own PR.

### 4. Minor: PR hygiene

- PR title `fix: sessions` is vague — suggest `fix(web): align dashboard Session type with gateway API response`
- PR template sections (Security Impact, Validation Evidence, i18n Follow-Through, Rollback Plan) are unfilled

---

### What passed

- **CI**: All checks green
- **Privacy/data hygiene**: Clean
- **Architectural alignment**: No new deps, no footprint impact
- **Security**: No concerns

Thanks for the contribution — the core direction here is solid. The type alignment and dead-UI cleanup is the right call. Just needs the fixes above and this should be good to go.

---
*ZeroClaw PR Review Agent*

**Comment by ilteoood** [comment]
@JordanTheJet I'm inspecting the translation keys cleanup, while about the first bug is a false positive to me. It is referencing to 2 different handlers so that's normal that they are repeated.

**Comment by JordanTheJet** [comment]
@ilteoood Thanks for the quick i18n cleanup — that looks great!

On the `api.rs` change — I built and tested your branch and the sessions fix works well. One small thing: the `"name": meta.name` line in the `json!()` macro isn't needed since the `if let Some(name)` block right below it already handles setting `name` when present. The difference is:

- `"name": meta.name` in the macro serializes the `Option<String>` directly, which emits `"name": null` when `None`
- The `if let` block only adds `name` to the JSON when it's `Some`, omitting it entirely otherwise

Since both are in the same handler (`handle_api_sessions_list`, same `filter_map` closure), the macro line is redundant and the `if let` pattern is the correct one to keep. I'd suggest just dropping the `"name": meta.name` line from the `json!()` macro — I tested the build without it and everything works the same.

Not a major issue, just a cleanup to avoid the `null` emission. The rest of the PR looks good!

File: src/gateway/api.rs [hunk 1]
```diff
@@ -1297,6 +1297,7 @@ pub async fn handle_api_sessions_list(
                 "created_at": meta.created_at.to_rfc3339(),
                 "last_activity": meta.last_activity.to_rfc3339(),
                 "message_count": meta.message_count,
+                "name": meta.name
```
Comment (ilteoood) [inline src/gateway/api.rs]:
```suggestion
```

**Comment by ilteoood** [comment]
> @ilteoood Thanks for the quick i18n cleanup — that looks great!
> 
> On the `api.rs` change — I built and tested your branch and the sessions fix works well. One small thing: the `"name": meta.name` line in the `json!()` macro isn't needed since the `if let Some(name)` block right below it already handles setting `name` when present. The difference is:
> 
> - `"name": meta.name` in the macro serializes the `Option<String>` directly, which emits `"name": null` when `None`
> - The `if let` block only adds `name` to the JSON when it's `Some`, omitting it entirely otherwise
> 
> Since both are in the same handler (`handle_api_sessions_list`, same `filter_map` closure), the macro line is redundant and the `if let` pattern is the correct one to keep. I'd suggest just dropping the `"name": meta.name` line from the `json!()` macro — I tested the build without it and everything works the same.
> 
> Not a major issue, just a cleanup to avoid the `null` emission. The rest of the PR looks good!

@JordanTheJet it should be ok now!

**Review by JordanTheJet — APPROVED** [review]
Looks good!
