### PR TITLE
fix(channels/ACP): resolve defaultModel from config; null when unconfigured

### LINKED ISSUE #6012: [Bug]: ACP handle_initialize returns hardcoded fallback model instead of configured provider
### Affected component

channel

### Severity

S2 - degraded behavior

### Current behavior

`handle_initialize` in `crates/zeroclaw-channels/src/orchestrator/acp_server.rs` resolves `defaultModel` from `ProvidersConfig::fallback_provider()` but falls back to the hardcoded string `"anthropic/claude-sonnet-4.6"` when no provider is configured:

```rust
.unwrap_or_else(|| "anthropic/claude-sonnet-4.6".to_string());
```

ACP clients (e.g. agentic.nvim) receive this string during the `initialize` handshake and use it to populate UI or route requests. On non-Anthropic setups (Ollama, OpenRouter, local llamacpp, etc.) the advertised `defaultModel` silently lies — it says `anthropic/claude-sonnet-4.6` while the runtime will actually use whatever provider is configured.

### Expected behavior

`defaultModel` in the `initialize` response should reflect the actual configured model, or be omitted (`null` / absent) if no fallback provider is configured, so clients receive accurate capability information.

### Steps to reproduce

```bash
# 1. Configure a non-Anthropic provider, e.g. Ollama
#    providers.fallback = "ollama"
#    [providers.models.ollama]
#    name = "ollama"
#    model = "llama3.2"
# 2. Run the ACP server
zeroclaw acp
# 3. Send initialize request
echo '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{}}' | zeroclaw acp
# 4. Observe defaultModel in response
```

Expected: `"defaultModel": "llama3.2"` (or omitted)
Actual: `"defaultModel": "anthropic/claude-sonnet-4.6"`

### Impact

Affected users: anyone using ACP with a non-Anthropic provider
Frequency: always — hardcoded string is unconditional
Consequence: ACP clients display or route to the wrong model; may confuse users or cause silent misdirection in editor integrations

### Logs / stack traces

N/A — no error, incorrect value returned silently.

### ZeroClaw version

Introduced in #5958 (merged 2026-04-23)

### Rust version

_No response_

### Operating system

All

### Regression?

Yes, it worked before

### Pre-flight checks

- [x] I reproduced this on the latest master branch or latest release.
- [x] I redacted secrets, tokens, and personal data from all submitted content.

### PR DESCRIPTION
**Pull request by singlerider**
## Summary

- **Base branch:** `master`
- **What changed and why:** `handle_initialize` was falling back to the hardcoded string `"anthropic/claude-sonnet-4.6"` when `fallback_provider().model` was `None`. ACP clients (e.g. agentic.nvim) receive `defaultModel` during the `initialize` handshake and use it to populate UI or route requests — so on any non-Anthropic setup the advertised model silently lied. Changed to emit `null` when no provider is configured, so clients can distinguish "not set" from a real value.
- **Scope boundary:** single function in `acp_server.rs`; no protocol changes, no config surface changes.
- **Blast radius:** ACP only. Clients that previously received `"anthropic/claude-sonnet-4.6"` as a fallback will now receive `null` when no provider is configured — a breaking fix for the incorrect behavior.
- **Linked issue(s):** Closes #6012.

## Validation Evidence (required)

```
cargo fmt --all -- --check
<no output>

cargo clippy -p zeroclaw-channels --all-targets -- -D warnings
Finished `dev` profile [unoptimized + debuginfo] target(s) in 16.04s

cargo test -p zeroclaw-channels
test result: ok. 929 passed; 0 failed (2 pre-existing orchestrator failures unrelated to this change)
```

New tests:
- `handle_initialize_default_model_null_when_unconfigured` — asserts `null` on `Config::default()`
- `handle_initialize_default_model_reflects_configured_provider` — asserts the configured model string is returned

## Security & Privacy Impact (required)

- New permissions, capabilities, or file system access scope? No.
- New external network calls? No.
- Secrets / tokens / credentials handling changed? No.
- PII, real identities, or personal data in diff, tests, fixtures, or docs? No.

## Compatibility (required)

- Backward compatible? No — ACP clients that depended on the hardcoded fallback as a signal will receive `null` instead. This is intentional: the previous behavior was incorrect.
- Config / env / CLI surface changed? No.

## Rollback (required for `risk: medium` and `risk: high`)

- **Fast rollback command/path:** `git revert 42a50cbe`
- **Feature flags or config toggles:** None.
- **Observable failure symptoms:** ACP clients receiving `null` for `defaultModel` instead of a hardcoded Anthropic model string on unconfigured instances.

## i18n Follow-Through

N.A. — behavior fix only; no user-facing strings or docs changed.

### CODE REVIEW

File: crates/zeroclaw-channels/src/orchestrator/acp_server.rs [hunk 1]
```diff
@@ -224,12 +224,13 @@ impl AcpServer {
...
     fn handle_initialize(&self, _params: &Value) -> RpcResult {
-        let default_model = self
+        let default_model: Value = self
             .config
             .providers
             .fallback_provider()
             .and_then(|e| e.model.clone())
-            .unwrap_or_else(|| "anthropic/claude-sonnet-4.6".to_string());
+            .map(|m| serde_json::json!(m))
+            .unwrap_or(Value::Null);
```
Comment (tidux) [inline crates/zeroclaw-channels/src/orchestrator/acp_server.rs]: Is making this null the correct thing to do here?  Every place that touches the fallback model now has to add null checks that weren't there before.

File: crates/zeroclaw-channels/src/orchestrator/acp_server.rs [hunk 2]
```diff
@@ -738,4 +739,32 @@ mod tests {
...
+
+    #[test]
+    fn handle_initialize_default_model_reflects_configured_provider() {
+        use zeroclaw_config::schema::ModelProviderConfig;
+        let mut config = Config::default();
+        config.providers.fallback = Some("myprovider".to_string());
+        config.providers.models.insert(
+            "myprovider".to_string(),
+            ModelProviderConfig {
+                model: Some("llama3.2".to_string()),
```
Comment (tidux) [inline crates/zeroclaw-channels/src/orchestrator/acp_server.rs:816]: This is what I mean, adding new null checks like Some and unwrap() to things that were not nullable before concerns me.

**Review by tidux — CHANGES_REQUESTED** [review]

**Review by WareWolf-MoonWall — COMMENTED** [review]
Reviewed at `42a50cbe618f4accb15c98df4cce21c19b857f14`.

tidux holds an active CHANGES_REQUESTED, so I'm posting a comment rather than a verdict. I've read the full diff, the inline threads, and the local source. I want to put my read of the open question on the record, because I think it changes the picture.

---

**On tidux's concern — "every place that touches the fallback model now has to add null checks"**

I don't think that's what's happening here, and I want to be specific about why.

`default_model` is a local variable scoped entirely within `handle_initialize`. It is used in exactly one place: as the value for the `"defaultModel"` key in the `serde_json::json!` response builder at the end of the function. It is not returned to a caller as a `String`, not stored, and not passed to any other method. Changing its type from `String` to `Value` does not affect any other code path in the crate — the variable dies when the function returns.

The `Some(...)` patterns in the test code are not new null checks in production. `ModelProviderConfig.model` was already `Option<String>` before this PR. The test is just constructing the config struct correctly to exercise the "provider configured" branch — you have to use `Some("llama3.2".to_string())` because that's what the field type requires. That's not adding nullability; it's the existing type surfacing in test setup.

So in my read: the scope of this change is as narrow as the PR description says. The null does not propagate.

@tidux — I'd ask you to look at lines 224–245 of `acp_server.rs` in context and confirm whether you see a propagation path I'm missing. If there isn't one, this thread is worth closing so the fix can move.

---

**On the fix itself**

The approach is correct. `handle_initialize` was lying to ACP clients — any non-Anthropic setup received `"anthropic/claude-sonnet-4.6"` as the advertised model regardless of what was actually configured. ACP clients (the PR names `agentic.nvim`) use `defaultModel` from the handshake to populate UI and route requests, so the lie had real downstream effects.

Emitting `null` when no provider is configured is the right semantic choice. It lets clients distinguish "not configured" from a real model name. Omitting the key entirely would be ambiguous (is it unsupported? unknown?). `null` is explicit.

The two new tests are well-targeted:
- `handle_initialize_default_model_null_when_unconfigured` covers the previously-broken case with `Config::default()` — the exact failure mode from #6012.
- `handle_initialize_default_model_reflects_configured_provider` covers the configured case with a non-Anthropic provider name and model, which is exactly the setup that would have silently received the wrong model before.

Both tests assert on the right JSON path (`result["capabilities"]["defaultModel"]`). Good test names, good failure messages.

**CI failures:** The two failing checks are the pre-existing RUSTSEC-2026-0104 advisory scan and the CI required-checks gate that depends on it. Neither is caused by this PR — all 10 code-quality checks are green.

---

🟡 **Labels not set**

`risk:*` and `size:*` are not on the sidebar. For this change the right calls are `risk: low` and `size: XS`. Set them via the sidebar.

---

Once the tidux thread is resolved and labels are set, I have nothing else blocking this. I'd approve at that point.

**Comment by tidux** [comment]
@WareWolf-MoonWall that potential null field gets sent to the ACP client.  `handle_request()` matches on `initialize` and invokes `handle_initialize()`, which builds an RPC response potentially containing a null default model, and passes it back out to `handle_request()` and then `write_result()`, which calls `write_json()`, which writes to `tokio::io::stdout()` which is read by the ACP client.  We're counting on "no defined default model" being a valid initialization state that ACP clients will accept from an ACP server.  It is so far in my testing but I haven't tested all the major ACP clients yet.  The [spec docs](https://agentclientprotocol.com/protocol/schema#initialize) are unclear.

**Comment by singlerider** [comment]
@tidux @WareWolf-MoonWall — looked into the spec question.

`defaultModel` isn't in the ACP spec at all. The `InitializeResponse` schema doesn't define it — model selection is post-handshake via `session/set_config_option`. So the "spec is unclear" point is moot; this is a zeroclaw extension and we own the semantics.

That said, @tidux's instinct to question it was right. Sending `null` for a custom field no client asked for is worse than not sending it. An absent key gets ignored; `null` requires handling.

019ae048 omits `defaultModel` from `capabilities` entirely when unconfigured. Test updated to match.

**Review by WareWolf-MoonWall — COMMENTED** [review]
Reviewed at `019ae048`.

This is a re-review after singlerider's latest commit and comment. I also want to put something on the record about my own prior position.

---

**On my previous comment — I got the null-vs-absent argument wrong**

In my earlier comment I wrote:

> "Emitting `null` when no provider is configured is the right semantic choice. It lets clients distinguish 'not configured' from a real model name. Omitting the key entirely would be ambiguous (is it unsupported? unknown?). `null` is explicit."

That reasoning was wrong, and I want to say so clearly.

The argument holds for **spec-defined fields** — when a field is part of a wire protocol and clients are expected to handle all its states, `null` can be a meaningful signal. But `defaultModel` is not in the ACP spec. singlerider checked the `InitializeResponse` schema at agentclientprotocol.com and confirmed it: this is a zeroclaw extension. For extension fields, the convention is the opposite of what I argued — include the key when you have a value, omit it when you don't. A client that doesn't know about the extension ignores an absent key with zero handling. A `null` value requires the client to handle a state they may not have written code for.

I was also right that the Rust null didn't propagate — `default_model` was always scoped to `handle_initialize` — but that missed where tidux's concern had actually landed by the end of their follow-up. Their real question was about what gets sent on the wire, and their instinct that something was off was correct. It just took singlerider's spec lookup to pin down exactly why.

---

**On `019ae048`**

The revised approach is correct. Building `capabilities` as a mutable object and conditionally inserting `defaultModel` only when a model is configured is the right pattern for extension fields. The key is present when it has meaning and absent when it doesn't — clients get no field to mishandle.

The test rename from `handle_initialize_default_model_null_when_unconfigured` to `handle_initialize_default_model_absent_when_unconfigured` is precise. The assertion change from `.is_null()` to `.get("defaultModel").is_none()` tests the actual contract now. Both tests cover the right cases.

---

🟡 **Stale doc comment**

The table entry in the module header was updated in this PR to read:

```
| `initialize` | Handshake — returns server capabilities (incl. defaultModel or null) |
```

But `019ae048` removed the `null` path entirely — the field is now absent when unconfigured, never `null`. The comment describes the behavior from `42a50cbe`, not the current implementation. It should read something like:

```
| `initialize` | Handshake — returns server capabilities (incl. defaultModel when configured) |
```

Small fix, but the doc comment is now internally inconsistent with the code directly below it.

---

✅ **Labels — RESOLVED**

`risk: low` and `size: XS` are on the sidebar. That point from my prior review is closed.

---

@tidux — `019ae048` addresses the concern directly: the field is no longer sent when unconfigured. The spec question is also settled (it's not a spec field; we own the semantics entirely). Worth a re-review to see if this resolves your block.

File: crates/zeroclaw-channels/src/orchestrator/acp_server.rs (hunk 2 above)
Comment (tidux) [reply crates/zeroclaw-channels/src/orchestrator/acp_server.rs:816]: With the new fallback behavior this Some() is extraneous but not a blocker.

**Comment by tidux** [comment]
@WareWolf-MoonWall yup, good to go.

**Review by WareWolf-MoonWall — COMMENTED** [review]
Re-review at `5691cc9c585d62f1caf58d889df1d308396827dd`.

## Prior item — RESOLVED ✅

🟡 **Stale doc comment** — the table entry now reads:

```
| `initialize` | Handshake — returns server capabilities (incl. defaultModel when configured) |
```

That matches the implementation exactly. ✅

---

## Status check — tidux's CHANGES_REQUESTED

The conversation is clearly resolved: tidux reviewed `019ae048`, noted the `Some()` in test setup is "extraneous but not a blocker," and then posted "yup, good to go." in the thread. The substantive concern has been addressed.

However, the reviews API still shows tidux's original CHANGES_REQUESTED (posted at `42a50cbe`) as the active formal verdict — a subsequent COMMENTED review does not supersede it in GitHub's model. The sidebar will still show this PR as blocked until that review is formally dismissed or superseded.

@tidux — everything you raised is resolved and you've said you're good to go. Could you post an Approve (or explicitly dismiss your prior CHANGES_REQUESTED) so the PR metadata reflects that? Once the formal state is cleared I'll approve on my end — I have no remaining technical concerns on this diff.

---

🔵 **Minor stale text in PR body** — the Validation Evidence section still lists the old test name `handle_initialize_default_model_null_when_unconfigured`. The current code has `handle_initialize_default_model_absent_when_unconfigured`. Non-blocking, but worth updating for accuracy before merge.

**Review by tidux — APPROVED** [review]

**Review by theonlyhennygod — APPROVED** [review]
## Comprehension Summary

**What:** Fixes `handle_initialize` in the ACP server to resolve `defaultModel` from the configured provider rather than hardcoding `"anthropic/claude-sonnet-4.6"`. When no provider is configured, the `defaultModel` field is omitted entirely from the response (rather than sending null or a wrong value). Also updates the module doc comment to match.

**Why:** ACP clients (e.g., `agentic.nvim`) use the `defaultModel` from the handshake response to populate UI and route requests. The hardcoded Anthropic model was incorrect for any non-Anthropic configuration and misleading when no provider was configured at all. Fixes #6012.

**Blast radius:** Only `handle_initialize` in `crates/zeroclaw-channels/src/orchestrator/acp_server.rs`. No changes to provider traits, routing logic, or other ACP methods. The `capabilities` JSON structure is identical except `defaultModel` is now conditional.

---

## Review

The prior review cycle between @tidux and @WareWolf-MoonWall was thorough and all concerns have been resolved:
- tidux's CHANGES_REQUESTED was addressed (null vs. absent semantics settled in favor of absent for extension fields) and tidux posted a formal APPROVE.
- WareWolf-MoonWall's stale doc comment finding was fixed in the latest commit.
- Labels are correctly set.

### Independent verification

1. The `fallback_provider().and_then(|e| e.model.clone())` correctly produces `None` when unconfigured and `Some(model)` when configured.
2. The conditional insertion `if let Some(model) = default_model { capabilities["defaultModel"] = ... }` is the right pattern for an extension field per ACP conventions (include when meaningful, omit when not).
3. Both tests are well-targeted: the unconfigured case asserts the key is absent (`.get("defaultModel").is_none()`), the configured case asserts the correct model value appears.
4. CI is fully green including CI Required Gate.
5. No privacy/PII concerns — test values are clearly synthetic.

**Security assessment:** No security impact identified. The change affects a JSON response field in a handshake; no access control, authentication, or secret handling is modified.

**Performance assessment:** No performance impact identified. Conditional JSON field insertion has negligible cost.

---

## Findings

None. The code is correct, well-tested, and all prior review feedback has been addressed.

---

## Verdict: Ready to merge

This PR is ready for maintainer merge. The fix is minimal, correct, well-tested, and has been through a productive multi-round review that resolved all open questions. CI is green and both reviewer concerns are resolved.

Thank you @singlerider for the thoughtful fix and for working through the null-vs-absent design discussion constructively.
