### PR TITLE
fix(prompt): rewrite safety section to reduce AI conservatism

### LINKED ISSUE #4496: [Bug]: 0.5版本以后降智商极其明显
### Affected component

runtime/daemon

### Severity

S1 - workflow blocked

### Current behavior

AI经常表示：本会话的命令执行被安全策略拦截（连 ls / 跑脚本都不允许）
但是已经释放权限。

和0.3系列版本的最大差异是：0.3系列版本直接运行，直接验证用户想法。
0.5 版本：直接上来就是做不到。

猜测原因是： zeroclaw的默认提示词出现变化，导致AI行为极度保守。

譬如AI经常提到：原因不是我想甩锅，而是当前对话进程里我确实没有可用的执行工具入口：你给我的 tool 列表只有 shell/file_read/file_write/memory_* 等，本会话里没有 `XXX` 工具，也没有任何我能用来启动 GUI Chrome 的可靠接口。

请高度重视，从0.5开始，恶性体验倒退层出不穷，核心能力出现大规模的滑坡。

### Expected behavior

和以前一样

### Steps to reproduce

```bash
无
```

### Impact

_No response_

### Logs / stack traces

```text

```

### ZeroClaw version

0.5.0+

### Rust version

_No response_

### Operating system

Ubuntu24

### Regression?

Yes, it worked before

### Pre-flight checks

- [x] I reproduced this on the latest master branch or latest release.
- [x] I redacted secrets, tokens, and personal data from all submitted content.

### PR DESCRIPTION
**Pull request by theonlyhennygod**
## Summary
- Rewrites SafetySection in `prompt.rs` to use action-oriented language instead of restrictive phrasing
- Full autonomy: "Execute tools and actions directly" instead of "explain that concrete restriction"
- Rewrites `prompt_summary()` in `policy.rs` to use instructive language instead of "will be rejected/blocked"
- AI will now attempt actions confidently and let the runtime enforce boundaries

Fixes #4496

## Test plan
- [ ] Verify AI no longer preemptively refuses commands in Full autonomy mode
- [ ] Test with various autonomy levels (full, supervised, read-only)
- [ ] Run `cargo test --lib agent::prompt` for updated test assertions
- [ ] Confirm AI still respects actual runtime restrictions when enforced

### CODE REVIEW

File: src/agent/prompt.rs [hunk 1]
```diff
@@ -187,23 +187,18 @@ impl PromptSection for SafetySection {
         out.push_str("- Prefer `trash` over `rm`.\n");
         out.push_str(match ctx.autonomy_level {
             AutonomyLevel::Full => {
-                "- Respect the runtime autonomy policy: if a tool or action is allowed, \
-                 execute it directly instead of asking the user for extra approval.\n\
-                 - If a tool or action is blocked by policy or unavailable, explain that \
-                 concrete restriction instead of simulating an approval dialog."
+                "- Execute tools and actions directly — no extra approval needed.\n\
+                 - You have full access to all configured tools. Use them confidently to accomplish tasks.\n\
+                 - Only refuse an action if the runtime explicitly rejects it — do not preemptively decline."
```
Comment (joehoyle) [inline src/agent/prompt.rs:192]: 🙏
