### PR TITLE
fix(channels/telegram): send inline_keyboard for tool approval requests

### LINKED ISSUE #5778: [Bug]: (channels/telegram): inline_keyboard (reply_markup) missing in outgoing messages
### Affected component

runtime/daemon

### Severity

S1 - workflow blocked

### Current behavior

Description
The Telegram channel fails to display inline buttons for tool/skill approvals, even when the agent is in `AwaitingApproval` state.

Technical Analysis (Trace Logs)
I analyzed the `RUST_LOG=trace` output during the daemon execution. The logs confirm that the outgoing JSON payload to `api.telegram.org/bot.../sendMessage` **does not contain the `reply_markup` object**. 

It appears that `src/channels/telegram.rs` is missing the logic to attach the `inline_keyboard` metadata provided by the orchestrator to the final Telegram message.

Environment
- **Architecture:** aarch64 (Orange Pi Zero 2)
- **Version:** Latest master

Observation:
Even though the session state indicates an action that requires approval, the subsequent POST request to sendMessage (verified via full TRACE monitoring) lacks the reply_markup JSON field. The LLM (Gemma-4) provided the correct intent, but the Telegram channel failed to serialize the buttons.

### Expected behavior

When an agent triggers a tool or skill that requires manual approval, the Telegram channel should send a message containing an inline_keyboard (via reply_markup) with "Approve" and "Deny" buttons. Clicking these buttons should allow the user to authorize or reject the action directly through the Telegram UI, without having to type manual text commands.

### Steps to reproduce

```bash
1. Connect a Telegram bot.
2. Trigger an action that requires manual approval (e.g., a restricted tool call).
3. The bot reacts with a green tick, but no inline buttons appear in the chat.
4. Manually typing "ok" results in a "Denied by user" error.
```

### Impact

This bug completely breaks the Human-in-the-loop (HITL) workflow on Telegram. Since restricted tools and skills require manual approval to execute, the absence of inline buttons makes it impossible for the user to authorize any sensitive action.
Furthermore, manual text input (like typing "ok" or "approve") is not recognized as a valid approval signal, effectively locking the user out of any advanced capabilities or secure operations. This renders the Telegram channel unusable for any agent deployment that requires safety gates or operator supervision.

### Logs / stack traces

```text
### Relevant Log Output
Here is the sequence showing the bot generating a reply but failing to attach the `reply_markup`:


// The bot completes the LLM call after a long processing time
2026-04-15T17:15:34.978717Z  INFO zeroclaw_channels::orchestrator: ⏱ LLM call completed llm_call_ms=45668 total_ms=130679
🤖 Reply (130769ms): Bentornato! Sì, esatto... [truncated]

// The bot reaches out to Telegram API
2026-04-15T17:15:35.069241Z TRACE hyper_util::client::legacy::pool: take? ("https", api.telegram.org)
2026-04-15T17:15:35.075735Z TRACE hyper_util::client::legacy::pool: take? ("https", generativelanguage.googleapis.com)
```

### ZeroClaw version

Latest Master / bf5873c0

### Rust version

rustc 1.94.1 (e408947bf 2026-03-25)

### Operating system

Build: CachyOS (Arch-based) via Distrobox / Target: Orange Pi Zero 2 (aarch64)

### Regression?

Unknown

### Pre-flight checks

- [x] I reproduced this on the latest master branch or latest release.
- [x] I redacted secrets, tokens, and personal data from all submitted content.

### PR DESCRIPTION
**Pull request by abhijeet117**
## Why

In supervised mode, the Telegram channel silently auto-denied every tool approval request because there was no interactive operator to approve them. Users on Telegram had no way to approve tool calls — the agent was effectively locked out of supervised tools when accessed via Telegram.

## What changed

| Crate | Change |
|-------|--------|
| `zeroclaw-api` | Added `ChannelApprovalRequest`, `ChannelApprovalResponse` types and `Channel::request_approval()` default method |
| `zeroclaw-channels` (Telegram) | Implemented `request_approval()` with inline keyboard buttons; updated `listen()` to handle `callback_query` updates |
| `zeroclaw-channels` (orchestrator) | Passes channel reference to `run_tool_call_loop` |
| `zeroclaw-runtime` (agent loop) | Threaded `channel: Option<&dyn Channel>` through `agent_turn`/`run_tool_call_loop`; approval hook tries channel approval before auto-deny |
| `zeroclaw-runtime` (delegate) | Added `None` channel parameter for subagent calls |

## How it works

1. When the agent loop encounters a tool needing approval in non-interactive mode, it calls `channel.request_approval()` on the active channel
2. The default `Channel` trait implementation returns `Ok(None)` (unsupported) — preserving existing auto-deny behavior for all other channels
3. `TelegramChannel::request_approval()` sends a message with `reply_markup` containing an inline keyboard (Approve / Deny / Always)
4. A oneshot channel is registered in a `pending_approvals` map **before** the message is sent (race-safe)
5. `listen()` now accepts `callback_query` updates alongside `message` updates — when a matching callback arrives, it resolves the oneshot and calls `answerCallbackQuery`
6. The approval flow awaits with a 120s timeout; on timeout, auto-denies

## Checklist

- [x] Non-breaking: `Channel::request_approval()` has a default impl — all 30+ channels unaffected
- [x] Race-safe: oneshot registered before `sendMessage` fires
- [x] Explicit action matching: only `approve`/`deny`/`always` are handled; unknown actions are logged and ignored
- [x] `answerCallbackQuery` failures logged at warn level
- [x] Unit tests for callback_data parsing, oneshot delivery, and response mapping
- [x] Follows conventional commit format

Closes #5778

### CODE REVIEW

**Comment by ErCondor1886** [comment]
I tested PR #5790 on my aarch64 environment. It successfully triggers the inline buttons, which is great!

However, I found a regression: it crashes with a 400 Bad Request: can't parse entities error whenever the tool name or arguments contain special characters like _ or . (e.g., using a filename like test_bottoni.txt). The message fails to send entirely in these cases.

I suggest switching the parse_mode to MarkdownV2 and implementing an escaping function for tool_name and arguments_summary to ensure stability with any file path or shell command.

File: crates/zeroclaw-api/src/channel.rs [hunk 1]
```diff
@@ -1,8 +1,30 @@
...
+/// The operator's response to a channel-presented approval prompt.
+#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
+#[serde(rename_all = "lowercase")]
+pub enum ChannelApprovalResponse {
+    /// Execute this one call.
+    Approve,
+    /// Deny this call.
+    Deny,
+    /// Execute and add tool to session-scoped allowlist.
+    AlwaysApprove,
```
Comment (singlerider) [inline crates/zeroclaw-api/src/channel.rs:26]: `[suggestion]` `#[serde(rename_all = "lowercase")]` produces `"alwaysapprove"` for this variant, which is unusual and inconsistent with the CLI-side `ApprovalResponse::Always` that serializes to `"always"`. Consider either `#[serde(rename_all = "snake_case")]` (yields `"always_approve"`) or adding `#[serde(rename = "always")]` to this variant specifically. This affects the audit log format and any future REST API exposure of this type.

File: crates/zeroclaw-channels/src/telegram.rs [hunk 2]
```diff
@@ -3024,6 +3097,85 @@ Ensure only one `zeroclaw` process is using this bot token."
...
+                anyhow::bail!("Telegram sendMessage (approval) failed ({status}): {err}");
+            }
+            Err(e) => {
+                self.pending_approvals.lock().await.remove(&approval_id);
+                return Err(e.into());
+            }
+        }
+
+        // Wait up to 120 seconds for the user to tap a button.
+        let result = match tokio::time::timeout(Duration::from_secs(120), rx).await {
```
Comment (singlerider) [inline crates/zeroclaw-channels/src/telegram.rs]: `[suggestion]` The 120-second approval timeout is hardcoded. Deployments with slow operator response times (or with a bot used across time zones) may want to tune this. Consider pulling it from `TelegramConfig` or `AutonomyConfig` with a 120s default.

File: crates/zeroclaw-channels/src/telegram.rs [hunk 3]
```diff
@@ -3024,6 +3097,85 @@ Ensure only one `zeroclaw` process is using this bot token."
...
+    ) -> anyhow::Result<Option<zeroclaw_api::channel::ChannelApprovalResponse>> {
+        use zeroclaw_api::channel::ChannelApprovalResponse;
+
+        // Parse recipient for chat_id (may contain ":thread_id" suffix).
+        let chat_id = recipient.split_once(':').map_or(recipient, |(c, _)| c);
+
+        // Unique key embedded in callback_data so listen() can route the tap.
+        let approval_id = uuid::Uuid::new_v4().to_string();
+
+        let tool = Self::escape_html(&request.tool_name);
```
Comment (singlerider) [inline crates/zeroclaw-channels/src/telegram.rs:3125]: `[question]` A community tester (@ErCondor1886) reported "400 Bad Request: can't parse entities" with tool names containing `_` or `.` and suggested switching to MarkdownV2. The current implementation uses `parse_mode: HTML` with `escape_html()`, which correctly handles those characters (they are not HTML special chars). Was this already in place when the tester reported, or was HTML mode added after their comment? Just confirming we can close out their report.

**Review by singlerider — CHANGES_REQUESTED** [review]
**Comprehension summary:** Adds interactive tool approval for the Telegram channel in supervised mode. When the agent loop encounters a tool requiring approval in non-interactive mode, it calls `channel.request_approval()`. All 30+ existing channels get the default `Ok(None)` (preserving auto-deny). `TelegramChannel::request_approval()` sends an inline keyboard (Approve / Deny / Always); `listen()` was extended to handle `callback_query` updates and resolve the approval oneshot. The oneshot is registered before `sendMessage` to eliminate the tap-before-registration race. Blast radius: all six channel WebSocket integrations share the updated agent loop path; non-Telegram channels are unaffected by the new approval branch.

**Security/performance assessment:** The `AlwaysApprove` path correctly feeds into the session-scoped allowlist in `ApprovalManager`, not a persistent allowlist. `escape_html()` is applied to both `tool_name` and `arguments_summary` before embedding in the HTML message — this correctly handles the special characters reported by the community tester (underscore and dot are not HTML special characters; the escaping covers `<`, `>`, `&`, `"`, `'`). `summarize_args` truncates per-value at 80 chars, preventing oversized Telegram messages. Race condition between button tap and oneshot registration is correctly avoided by inserting the sender before calling `sendMessage`. No new permissions, network endpoints, or secret handling.

File: crates/zeroclaw-api/src/channel.rs (hunk 1 above)
Comment (abhijeet117) [reply crates/zeroclaw-api/src/channel.rs:26]: Good catch — switched to `#[serde(rename = "always")]` on `AlwaysApprove` specifically, so it serializes to `"always"` matching the CLI-side `ApprovalResponse::Always` token. Kept the enum-level `rename_all = "lowercase"` for the other two variants (`"approve"`, `"deny"`), which also keeps the callback_data strings we emit on the inline keyboard (`approval:<uuid>:approve` / `:deny` / `:always`) symmetric with what gets logged. Updated `channel_approval_response_serde_roundtrip` to assert the new encoding.

Fixed in f31bf310.

File: crates/zeroclaw-channels/src/telegram.rs (hunk 2 above)
Comment (abhijeet117) [reply crates/zeroclaw-channels/src/telegram.rs]: Done — timeout now flows from config. Added `channels.telegram.approval_timeout_secs` to `TelegramConfig` (u64, `#[serde(default = "default_telegram_approval_timeout_secs")]` → 120), a `TelegramChannel::with_approval_timeout_secs` builder, and threaded it through `build_channel_by_id` + `collect_configured_channels`. `request_approval` now reads `self.approval_timeout_secs` instead of the hardcoded `Duration::from_secs(120)`. Deployments can tune per-channel without code changes:

```toml
[channels.telegram]
approval_timeout_secs = 300   # 5-minute window for slow operators
```

New unit test `approval_timeout_defaults_to_120_and_is_overridable` covers the builder contract. Fixed in f31bf310.

File: crates/zeroclaw-channels/src/telegram.rs (hunk 3 above)
Comment (abhijeet117) [reply crates/zeroclaw-channels/src/telegram.rs:3125]: Confirming: HTML mode with `escape_html()` was in the original PR commit (56d93186) — it was the chosen encoding from day one, not a post-report patch. `escape_html` covers `<`, `>`, `&`, `"`, `'`, which is exactly the HTML parse-entity set Telegram's server-side parser cares about; `_` and `.` are not special in HTML mode, so `test_bottoni.txt` and similar tool names / filenames round-trip cleanly without any additional escaping.

The MarkdownV2 path would've required escaping ~18 metacharacters (`_ * [ ] ( ) ~ `` > # + - = | { } . !`) and is more brittle for arbitrary tool arguments, so we stayed on HTML. Safe to close out @ErCondor1886's report — the failure mode they hit was specific to the MarkdownV2 default in Telegram's older examples, not to our implementation.

**Comment by abhijeet117** [comment]
@ErCondor1886 thanks for testing on aarch64! Quick follow-up on the `can't parse entities` error — the current implementation is using `parse_mode: HTML` (not MarkdownV2) with an `escape_html()` helper applied to both `tool_name` and `arguments_summary` before they're interpolated into the template. In HTML mode, `_` and `.` aren't special characters, so a name like `test_bottoni.txt` goes through verbatim without needing any escape.

Could you retry on the latest commit (`f31bf310`) with the same tool name / path that reproduced earlier? If the 400 still fires, please paste the raw `sendMessage` body from your logs and the full Telegram error response — that'll tell us whether it's actually HTML-related or whether there's another non-ASCII sequence sneaking through that escape_html doesn't cover.

**Comment by abhijeet117** [comment]
@singlerider ready for another look when you have a minute. Addressed both change-requested items:

1. **Serde consistency (r3097124694)** — `AlwaysApprove` now uses `#[serde(rename = "always")]` to match CLI `ApprovalResponse::Always` serialization. Test updated (`channel_approval_response_serde_roundtrip`). Commit f31bf310.
2. **Hardcoded 120s timeout (r3097124699)** — pulled into `channels.telegram.approval_timeout_secs` (u64, serde default 120). New `TelegramChannel::with_approval_timeout_secs` builder; wired through `build_channel_by_id` and `collect_configured_channels`. New test `approval_timeout_defaults_to_120_and_is_overridable`. Commit f31bf310.
3. **HTML mode / MarkdownV2 (r3097124702)** — replied inline confirming HTML was original; escape_html already covers all HTML entities and `_`/`.` are non-special in HTML mode.

Also:
- fmt pass in 68939b30
- merged `master` forward (5 commits, clean ort merge — no conflicts) in a70117d5

All 20 CI checks green. Branch no longer behind.

**Review by singlerider — APPROVED** [review]
Thanks for the thorough iteration on this one, @abhijeet117 — all three items from the prior review are cleanly resolved.

### Comprehension summary
Adds interactive tool-call approval for Telegram in supervised mode. Extends the `Channel` trait with a `request_approval()` default method (all other channels return `Ok(None)`, preserving existing auto-deny behavior). `TelegramChannel` implements it by sending an inline keyboard (Approve / Deny / Always), registering a oneshot before the message is sent (race-safe), and resolving it when `callback_query` arrives in `listen()`. Timeout is configurable via `channels.telegram.approval_timeout_secs` (default 120s). The runtime agent loop now threads `channel: Option<&dyn Channel>` through `agent_turn`/`run_tool_call_loop` to reach the approval hook.

### What was verified
- CI fully green on Apr 17 run — all 20 checks pass
- All three prior findings resolved:
  - `AlwaysApprove` serializes to `"always"` via `#[serde(rename = "always")]`, consistent with CLI-side `ApprovalResponse::Always` ✅
  - Timeout configurable via `channels.telegram.approval_timeout_secs`, wired through config schema, both channel builders, and `TelegramChannel::with_approval_timeout_secs` ✅
  - HTML mode with `escape_html()` confirmed correct — `_` and `.` are non-special in HTML mode; the 400 report was not reproduced with this implementation ✅
- Race safety: oneshot inserted into `pending_approvals` before `sendMessage` fires ✅
- Cleanup correct: map entry removed on sendMessage failure and on timeout/sender-drop ✅
- `rsplit_once(':')` correctly handles UUID approval IDs (hyphens) ✅
- `callback_query` updates subscribed via `allowed_updates`; `continue` skips regular message processing path ✅
- All test struct literals updated with `approval_timeout_secs: 120` ✅

### Security / performance assessment
No new permissions or file system access. The `pending_approvals` map is bounded by concurrent in-flight approval requests (one entry per active approval); entries are always cleaned up on resolution, timeout, or send failure. The approval message is HTML-escaped. No credentials handling changes.

Note for @jordanthejet: this PR threads `channel: Option<&dyn Channel>` through `agent_turn` and `run_tool_call_loop` in the runtime crate — a high-risk path per `AGENTS.md`. The implementation is correct and well-tested, but the final merge decision should be yours.

This PR is ready for maintainer merge.
