### PR TITLE
fix(channels/acp): correct tool output formatting

### LINKED ISSUE #6018: [Bug]: ACP always reports tool usage as other()
### Affected component

runtime/daemon

### Severity

S2 - degraded behavior

### Current behavior

The ACP server does not accurately report tool names. A demonstration of the effect:

Image

### Expected behavior

The ACP server should accurately report tool invocations.

### Steps to reproduce

```bash
1. zeroclaw onboard
2. enable filesystem access to wherever your repo is (may require disabling workspace-only)
3. open editor in workspace that zeroclaw has access to
4. activate ACP-enabled editor
5. open ACP dialogue window/area
6. instruct the agent to do something that results in a tool use
```

### Impact

Affected users: ACP users
Frequency: always
Consequence: limited visibility into any tool call that doesn't result in a permission prompt, potential unwanted code edits

### Logs / stack traces

```text

```

### ZeroClaw version

5c81d4e4c46a8691a6b202c2a5e5eee277c370f4

### Rust version

rustc 1.92.0

### Operating system

macOS 26

### Regression?

Unknown

### Pre-flight checks

- [x] I reproduced this on the latest master branch or latest release.
- [x] I redacted secrets, tokens, and personal data from all submitted content.

### PR DESCRIPTION
**Pull request by tidux**
## Summary

- **Base branch:** `master`
- **What changed and why:** 
- The ACP server was transmitting tool call events incorrectly, not being able to show their output or accurately describing their names and actions.
- This turned out to be a bug in the way the ACP server was presenting the events - technically correct, but not what ACP clients were expecting.
- Correcting this required guaranteeing we weren't reusing tool call event IDs, so this resolves an old TODO and gives every tool call its own UUID.
- **Scope boundary:**
- Other channels are left alone aside from ACP and websocket.
- **Blast radius:** **LARGE**.  Impacts agent.rs and the websocket gateway tool caller by changing the payload format.
- **Linked issue(s):** Closes #6018 

## Validation Evidence (required)

It works.

Screenshot 2026-04-22 at 11 08 20 PM

```bash
% cargo fmt --all -- --check
# no output
% cargo clippy --all-targets -- -D warnings
    Checking zeroclaw-config v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-config)
    Checking zeroclaw-providers v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-providers)
    Checking zeroclaw-memory v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-memory)
    Checking zeroclaw-tui v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-tui)
    Checking zeroclaw-tools v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-tools)
    Checking zeroclaw-runtime v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-runtime)
    Checking zeroclaw-hardware v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-hardware)
    Checking zeroclaw-channels v0.7.3 (/Users/tidux/src/zeroclaw/crates/zeroclaw-channels)
    Checking zeroclawlabs v0.7.3 (/Users/tidux/src/zeroclaw)
    Finished [`dev` profile [unoptimized + debuginfo]](https://doc.rust-lang.org/cargo/reference/profiles.html#default-profiles) target(s) in 49.20s
% cargo test
<snip>
test integration::memory_restart::sqlite_memory_store_same_key_deduplicates ... ok
test integration::telegram_attachment_fallback::multiple_attachments_independent_fallback ... ok
test integration::telegram_finalize_draft::finalize_draft_treats_not_modified_as_success ... ok
test integration::telegram_finalize_draft::finalize_draft_sends_fresh_message_after_successful_delete ... ok
test integration::telegram_attachment_fallback::photo_url_failure_falls_back_to_text_link ... ok
test integration::memory_comparison::compare_recall_speed ... ok

test result: ok. 159 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.22s
<snip>
test system::full_stack::system_tool_arguments_passed_correctly ... ok
test system::full_stack::system_simple_text_response ... ok
test system::full_stack::system_tool_execution_flow ... ok
test system::full_stack::system_multi_turn_conversation ... ok
test system::full_stack::system_parallel_tool_execution ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

## Security & Privacy Impact (required)

- New permissions, capabilities, or file system access scope? No
- New external network calls? No
- Secrets / tokens / credentials handling changed? No
- PII, real identities, or personal data in diff, tests, fixtures, or docs? No

## Compatibility (required)

- Backward compatible? **No**
- Config / env / CLI surface changed? No
- **Breaking change:** `zeroclaw_api::agent::TurnEvent::{ToolCall, ToolResult}` now include a required `id: String` field for stable tool-call/result correlation. Any external consumer exhaustively pattern-matching these enum variants must update those matches to bind or ignore the new field.
- **Migration path:** Update matches from `TurnEvent::ToolCall { name, args }` / `TurnEvent::ToolResult { name, output }` to include `id` or `..`.
- **Why this is required:** ACP and websocket clients need a stable per-call identifier so repeated tool invocations in the same turn can be correlated correctly.
- **Call-site audit:** In-tree consumers were updated and validated:
  - `crates/zeroclaw-channels/src/orchestrator/acp_server.rs`
  - `crates/zeroclaw-gateway/src/ws.rs`
  - `crates/zeroclaw-runtime/src/agent/agent.rs` tests and streamed-event handling
- **Out-of-tree risk:** Third-party consumers of `zeroclaw-api` that match `TurnEvent` directly will need the same update.

## Rollback (required for `risk: medium` and `risk: high`)

- **Fast rollback command/path:** `git revert 4809d78d01d308dea17795311efcb0987794d9fc`
- **Feature flags or config toggles:** None
- **Observable failure symptoms:** malformed tool messages, every tool call displayed as `other()` in ACP client, like so:

Screenshot 2026-04-22 at 6 55 53 PM

---

**Labels** live in the GitHub label UI, not in the body. Set `risk:*`, `size:*`, and scope labels via the sidebar. Auto-label corrections: add `risk: manual` and the intended label.

**Commit trailers** capture AI-assisted collaboration (`Co-Authored-By: Claude ...`) — no separate section needed.

**Privacy contract** (`docs/contributing/pr-discipline.md`) is a merge gate. Never commit real identities, secrets, personal emails, or PII in diff, tests, fixtures, or docs.

### CODE REVIEW

**Comment by tidux** [comment]
This is definitely not a docs PR, not sure why it got labeled that way.

**Review by Audacity88 — COMMENTED** [review]
Reviewed at `0ea7d47a`. First review on this PR. Labels corrected from `docs` to `bug`, `channel`, `risk: high` — touches `agent.rs` and `ws.rs` (high-risk paths per AGENTS.md).

**Conflict note:** This PR will conflict with #5705 (session abort + incremental persistence), which also modifies `TurnEvent`, `ws.rs`, and `agent.rs`. The conflict is mechanical — whoever merges second adds the other's field. Flagging so maintainers can sequence.

---

### 🟢 Stable IDs for tool call correlation

Adding `id: String` to `TurnEvent::ToolCall` and `ToolResult` solves a real problem. The previous approach used the tool name as `toolCallId`, which broke correlation when the same tool was called multiple times in one turn. UUID-based IDs with pre-assignment for provider-sourced calls are the right fix. The new test assertions (UUID format validation + call/result ID correlation) are a good addition.

---

### 🔴 `last_pre_executed_call_id` correlation breaks under parallel tool calls

`agent.rs:1118` uses a single `Option<String>` to track the last call ID, then `.take()`s it on result. This assumes strict interleaving: call A → result A → call B → result B. If two `PreExecutedToolCall` events arrive before their results, the first call's ID is overwritten and the correlation is silently lost (the `unwrap_or_else` fallback generates a new UUID, hiding the mismatch).

`parallel_tools` exists in config (`schema.rs:1434`) but isn't checked in the streaming loop. Even without parallel tools, a provider could theoretically emit events out of order.

Should use a `HashMap<String, String>` keyed by tool name or a `VecDeque` to track in-flight call IDs.

---

### 🟡 `map_tool_kind` is fragile and inefficient

The function guesses tool kind via `name.to_lowercase().contains(...)`. Issues:

- **Miscategorization:** `memory_forget` and `memory_purge` contain neither "delete" nor "remove" — they fall through to "other" instead of "delete". `cron_run` hits "run" → "execute" which is arguably correct but coincidental.
- **Called twice per tool:** Once for `ToolCall` (pending) and once for `ToolResult` (completed) with the same deterministic result. Each call allocates a new String via `to_lowercase()`.
- **Fragile for future tools:** Any tool whose name contains a substring from a higher-priority branch gets miscategorized.

A static map of known tool names to kinds (falling back to "other") would be more robust and faster.

---

### 🟡 ToolResult duplicates output in JSON

The ACP `tool_call_update` notification now includes both `rawOutput` and a `content` array wrapping the same output text:

```json
"rawOutput": "file1.txt\nfile2.txt",
"content": [{"type": "content", "content": {"type": "text", "text": "file1.txt\nfile2.txt"}}]
```

For large tool outputs (file contents, shell command results), this doubles the payload size on the wire. If both fields are required by the ACP spec, a comment explaining why would help. If not, one should be dropped.

---

### 🟡 Plan document should not be committed

`docs/superpowers/plans/2026-04-22-acp-tool-reporting-fix.md` is an implementation plan, not user-facing documentation. Plan documents go stale immediately after implementation. The PR description already captures the design rationale.

---

### 🟡 `TurnEvent` change is a breaking API change — should be documented

Adding `id` to `ToolCall` and `ToolResult` variants breaks all external pattern matches on `TurnEvent`. `zeroclaw-api` is the stable extension point per AGENTS.md. The PR description should note this as a breaking change with a call-site audit.

---

### 🔵 Should `TurnEvent` carry structured tool metadata?

With this PR, `TurnEvent::ToolCall` has `id`, `name`, and `args`. As more fields accumulate (kind, status, cancellation context from #5705), a nested struct would be cleaner than flat enum fields.

**Review by Audacity88 — CHANGES_REQUESTED** [review]
Reviewed at `0ea7d47a`. First review on this PR. Labels corrected from `docs` to `bug`, `channel`, `risk: high` — touches `agent.rs` and `ws.rs` (high-risk paths per AGENTS.md).

**Conflict note:** This PR will conflict with #5705 (session abort + incremental persistence), which also modifies `TurnEvent`, `ws.rs`, and `agent.rs`. The conflict is mechanical — whoever merges second adds the other's field. Flagging so maintainers can sequence.

---

### 🟢 Stable IDs for tool call correlation

Adding `id: String` to `TurnEvent::ToolCall` and `ToolResult` solves a real problem. The previous approach used the tool name as `toolCallId`, which broke correlation when the same tool was called multiple times in one turn. UUID-based IDs with pre-assignment for provider-sourced calls are the right fix. The new test assertions (UUID format validation + call/result ID correlation) are a good addition.

---

### 🔴 `last_pre_executed_call_id` correlation breaks under parallel tool calls

`agent.rs:1118` uses a single `Option<String>` to track the last call ID, then `.take()`s it on result. This assumes strict interleaving: call A → result A → call B → result B. If two `PreExecutedToolCall` events arrive before their results, the first call's ID is overwritten and the correlation is silently lost (the `unwrap_or_else` fallback generates a new UUID, hiding the mismatch).

`parallel_tools` exists in config (`schema.rs:1434`) but isn't checked in the streaming loop. Even without parallel tools, a provider could theoretically emit events out of order.

Should use a `HashMap<String, String>` keyed by tool name or a `VecDeque` to track in-flight call IDs.

---

### 🟡 `map_tool_kind` is fragile and inefficient

The function guesses tool kind via `name.to_lowercase().contains(...)`. Issues:

- **Miscategorization:** `memory_forget` and `memory_purge` contain neither "delete" nor "remove" — they fall through to "other" instead of "delete". `cron_run` hits "run" → "execute" which is arguably correct but coincidental.
- **Called twice per tool:** Once for `ToolCall` (pending) and once for `ToolResult` (completed) with the same deterministic result. Each call allocates a new String via `to_lowercase()`.
- **Fragile for future tools:** Any tool whose name contains a substring from a higher-priority branch gets miscategorized.

A static map of known tool names to kinds (falling back to "other") would be more robust and faster.

---

### 🟡 ToolResult duplicates output in JSON

The ACP `tool_call_update` notification now includes both `rawOutput` and a `content` array wrapping the same output text:

```json
"rawOutput": "file1.txt\nfile2.txt",
"content": [{"type": "content", "content": {"type": "text", "text": "file1.txt\nfile2.txt"}}]
```

For large tool outputs (file contents, shell command results), this doubles the payload size on the wire. If both fields are required by the ACP spec, a comment explaining why would help. If not, one should be dropped.

---

### 🟡 Plan document should not be committed

`docs/superpowers/plans/2026-04-22-acp-tool-reporting-fix.md` is an implementation plan, not user-facing documentation. Plan documents go stale immediately after implementation. The PR description already captures the design rationale.

---

### 🟡 `TurnEvent` change is a breaking API change — should be documented

Adding `id` to `ToolCall` and `ToolResult` variants breaks all external pattern matches on `TurnEvent`. `zeroclaw-api` is the stable extension point per AGENTS.md. The PR description should note this as a breaking change with a call-site audit.

---

### 🔵 Should `TurnEvent` carry structured tool metadata?

With this PR, `TurnEvent::ToolCall` has `id`, `name`, and `args`. As more fields accumulate (kind, status, cancellation context from #5705), a nested struct would be cleaner than flat enum fields.

**Comment by tidux** [comment]
@Audacity88 code and PR description updated to address review.

**Review by WareWolf-MoonWall — COMMENTED** [review]
## Re-review at 52ae40e7

Audacity88 reviewed at `0ea7d47a` and held with CHANGES_REQUESTED. The author pushed new commits and left a note that all items were addressed. I've read the full updated diff against each item. Summary below.

---

## Audacity88's Items — Status on Current Head

### 🔴 Parallel tool call correlation — RESOLVED ✅

The single `Option<String>` is gone. The new structure is:

```rust
let mut pre_executed_call_ids: HashMap<String, VecDeque<String>> = HashMap::new();
```

Each call pushes its UUID to the back of the tool-name keyed deque; each result pops from the front — FIFO per tool, which correctly handles interleaved calls from different tools arriving before their results. The `pre_executed_tool_results_keep_ids_when_calls_overlap` test exercises exactly the scenario Audacity88 described: `call_A, call_B, result_A, result_B` with two different tools, asserting that each tool's call ID and result ID match after the shuffle. That test is the right critical-path check for this fix.

### 🟡 `map_tool_kind` fragile and inefficient — RESOLVED ✅

Replaced entirely with a static exhaustive `match` over literal tool names. `memory_forget` and `memory_purge` are now correctly mapped to `"delete"`. `cron_run` is explicitly `"execute"`. No `to_lowercase()` allocation. `map_tool_kind_uses_explicit_tool_names` verifies the specific cases Audacity88 cited.

### 🟡 ToolResult duplicates output in JSON — RESOLVED ✅

`tool_call_update` now emits `rawOutput` only — the redundant `content` array is gone. The comment above the event loop was updated to explicitly note the design intent ("without duplicating large tool output in multiple fields on the wire"). The serialization test asserts `!json2.contains("\"content\"")` to lock this in.

### 🟡 Plan document committed — RESOLVED ✅

`docs/superpowers/plans/2026-04-22-acp-tool-reporting-fix.md` is not in the file list for the current head. Removed.

### 🟡 Breaking API change undocumented — RESOLVED ✅

The `Compatibility` section in the PR body now carries a complete account: the breaking change description, migration path (`include id or ..`), rationale (stable correlation for ACP/websocket clients), and an in-tree call-site audit listing all four updated files. The `zeroclaw-api` docblock also now includes the consumer guidance note.

### 🔵 TurnEvent structured metadata — Open

Not addressed in this PR, which is correct — it's a separate architectural question. Still on the table for a future refactor as the struct grows.

---

## New Findings

### 🔵 `unwrap()` on `tool_call_id` is safe today but fragile

At two sites in the non-streaming path (notify tool call, notify tool result), the code does:

```rust
let call_id = call.tool_call_id.as_ref().unwrap().clone();
// ... and:
let result_id = result.tool_call_id.as_ref().unwrap().clone();
```

The pre-assignment loop that runs immediately before guarantees `tool_call_id` is `Some` for every element in `calls`, and the results vector inherits the same IDs. The unwrap is safe given the current layout. The fragility is that if the loop is ever guarded, moved, or the results vector is constructed through a different path, this panics silently. A `.expect("tool_call_id was pre-assigned above")` with a message, or `.unwrap_or_else(|| uuid::Uuid::new_v4().to_string())` as a defensive fallback, would make the intent explicit and survive future refactoring. Not blocking — noting it because this is a high-risk file.

### 🔵 FIFO-per-name has a documented inherent limit worth capturing in a comment

The VecDeque approach is a substantial improvement and handles the realistic parallel-tool scenario correctly. The residual limitation is that if the *same tool* is called twice and the provider delivers results in reverse order (result for call 2 before result for call 1), the IDs would be misattributed — because name-based keying cannot distinguish which invocation a result belongs to without provider-level identifiers. This is not a regression from the previous code (which had no correlation at all), and fixing it fully would require provider-level per-call IDs surfaced through `StreamEvent`. Worth a one-line comment at the `HashMap<String, VecDeque<String>>` declaration so the next reader understands the design tradeoff and the known limit without having to reconstruct the reasoning.

### 🔵 `map_tool_kind` will drift silently as new tools are added

The `_ => "other"` fallback is safe — new tools degrade gracefully to the generic kind rather than panicking or erroring. The risk is silent miscategorisation in the ACP client UI (icons, UI affordances) that no test would catch. A short comment near the catch-all arm — something like `// New tools should be added above; "other" is the safe default for unrecognized names` — gives future contributors the right nudge without requiring a process change. Minor, but this file is likely to receive new entries regularly.

---

## Summary

All five actionable items from Audacity88's CHANGES_REQUESTED are addressed in the current head. The three 🔵 notes above are non-blocking. I'm commenting rather than approving since Audacity88's hold is still active — once they re-review and confirm the fixes land as intended, this should be in good shape to merge.

**Comment by WareWolf-MoonWall** [comment]
@JordanTheJet — milestone alignment needed: this PR (fix(channels/acp) — correct tool output formatting, breaking change to `TurnEvent` in `zeroclaw-api`) touches `zeroclaw-runtime`, `zeroclaw-gateway`, `zeroclaw-channels`, and `zeroclaw-api`. It does not fit v0.7.4 (no runtime/gateway), v0.7.5 (no runtime, no feature/fix work), or v0.8.0 (config schema/tier promotion scope). Please advise on milestone placement or deferral.

**Review by Audacity88 — APPROVED** [review]
All findings from my review are addressed:

- 🔴 **Parallel correlation** → `HashMap<String, VecDeque<String>>` replaces the single `Option`. Correct fix. ✅
- 🟡 **`map_tool_kind`** → explicit `match` on known tool names replaces substring heuristic. ✅
- 🟡 **Plan document** → removed from commit. ✅
- 🟡 **Content duplication** → `content[]` array dropped, only `rawOutput` remains. ✅
- 🟡 **Breaking change docs** → Compatibility section now documents the `TurnEvent` change with migration path and call-site audit. ✅

LGTM. Note the mechanical conflict with #5705 for merge sequencing.

**Comment by singlerider** [comment]
@tidux Can you resolve the conflicts and ping one of us after? This looks just about ready.

**Comment by tidux** [comment]
@singlerider @Audacity88 merge conflict resolved.  Wasn't actually a meaningful conflict, just overlapping line numbers on combinable changes.

**Comment by tidux** [comment]
Now that #5705 is merged this should be good to go, right?

File: crates/zeroclaw-config/src/policy.rs [hunk 1]
```diff
@@ -548,10 +548,8 @@ fn contains_unquoted_single_ampersand(command: &str) -> bool {
                 match ch {
                     '\'' => quote = QuoteState::Single,
                     '"' => quote = QuoteState::Double,
-                    '&' => {
-                        if chars.next_if_eq(&'&').is_none() {
-                            return true;
-                        }
+                    '&' if chars.peek().copied() != Some('&') => {
```
Comment (singlerider) [inline crates/zeroclaw-config/src/policy.rs]: 🔴 **[blocking]** This guard hoist is not equivalent to the original.

The original arm was:

```rust
'&' => {
    if chars.next_if_eq(&'&').is_none() {
        return true;
    }
}
```

`next_if_eq(&'&')` had a side effect: it CONSUMED the second `&` when the next char matched. The peek-only guard above does not consume. On input `&&`:

1. Iter 1: `ch = '&'`, peek = `Some('&')`, guard fails, falls through to `_ => {}`. Position advances by one.
2. Iter 2: `ch = '&'` (the second one), peek = `None`, guard succeeds, returns `true`.

So `&&` now reads as a lone unquoted `&` and the policy validator blocks legitimate AND chains. The existing test `policy::tests::command_injection_and_chain_blocked` at line 2440 of this file already covers this — `assert!(p.is_command_allowed("ls && echo done"))` — and fails on the current head:

```
test policy::tests::command_injection_and_chain_blocked ... FAILED
thread '...' panicked: assertion failed: p.is_command_allowed("ls && echo done")
```

Fix: keep the consumption side-effect. Either revert this arm to the original `if chars.next_if_eq(&'&').is_none()` form, or use an explicit two-char lookahead that explicitly consumes the second `&`. The clippy lint that suggests guard hoists (likely `clippy::collapsible_if`) doesn't understand that the inner condition has a side effect — this is a known false-positive class.

**Review by singlerider — CHANGES_REQUESTED** [review]
## Re-review at 990125b3

@Audacity88's CHANGES_REQUESTED at 0ea7d47a was closed with their APPROVED at 66730f42. @WareWolf-MoonWall's COMMENTED review at 52ae40e7 added three 🔵 non-blocking notes. I'm reviewing the three commits since 66730f42: 870c4db1 (master merge), 717d0d31 (`fix clippy errors`), and 990125b34 (`fix: satisfy current clippy checks`).

The ACP fixes themselves are still in good shape. The block here is on a clippy fixup commit that broke a security policy invariant.

---

### 🔴 [blocking] `contains_unquoted_single_ampersand` regresses on `&&` after the clippy "fix" in 717d0d31

`crates/zeroclaw-config/src/policy.rs:551`. The original arm:

```rust
'&' => {
    if chars.next_if_eq(&'&').is_none() {
        return true;
    }
}
```

was rewritten as:

```rust
'&' if chars.peek().copied() != Some('&') => {
    return true;
}
```

Those are not equivalent. `next_if_eq(&'&')` had a side effect: it CONSUMED the second `&` when present. The peek-only guard does not. On input `&&`:

1. Iter 1: ch = `&`. Guard checks peek = Some(`&`), guard fails, falls through to `_ => {}`. No char consumed beyond the first.
2. Iter 2: ch = `&`. Guard checks peek = None, guard succeeds. **Returns true.**

So `&&` now reads as a lone unquoted `&` and the policy validator blocks it. The existing test `policy::tests::command_injection_and_chain_blocked` in `policy.rs:2440` already covers this: `assert!(p.is_command_allowed("ls && echo done"))`.

I verified by checking out 990125b3 and running it:

```
test policy::tests::command_injection_and_chain_blocked ... FAILED
thread '...' panicked at crates/zeroclaw-config/src/policy.rs:2443:9:
assertion failed: p.is_command_allowed("ls && echo done")
```

Two other failures (`schema::tests::memory_config_pgvector_*`) are pre-existing on master and unrelated.

Fix is to keep the consumption side-effect. Either revert this specific arm to the original `if chars.next_if_eq(&'&').is_none()` form, or use an explicit two-char lookahead that consumes. The clippy lint that suggested the guard hoist (likely `clippy::collapsible_if`) does not understand that the inner condition has a side effect; this is a known false-positive class for that lint.

This is the only side-effect-bearing inner `if` in the clippy commits I checked. The other guard hoists (`irc.rs` CAP/AUTHENTICATE, `linkedin_client.rs` LINKEDIN_REFRESH_TOKEN, `onboarding.rs` KeyCode::Down) operate on pure conditions and are equivalent.

---

### Status of prior findings

@Audacity88's CHANGES_REQUESTED items, all confirmed RESOLVED ✅:
- 🔴 Parallel tool call correlation: `HashMap<String, VecDeque<String>>` replaces the single `Option`. Test `pre_executed_tool_results_keep_ids_when_calls_overlap` covers the interleaved-call scenario.
- 🟡 `map_tool_kind`: explicit match on tool names; `memory_forget` and `memory_purge` correctly map to `delete`.
- 🟡 ToolResult content duplication: `content[]` array dropped, `rawOutput` only.
- 🟡 Plan document: removed.
- 🟡 Breaking change documented: Compatibility section now carries the migration path and call-site audit.

@WareWolf-MoonWall's three 🔵 notes from 52ae40e7 are still open but explicitly non-blocking:
- `unwrap()` on `tool_call_id` is safe today, fragile to refactoring (suggested `.expect(...)` or fallback)
- FIFO-per-name has a known limit when the same tool's results arrive out of order (worth a comment at the HashMap declaration)
- `map_tool_kind` will drift silently as new tools are added (worth a comment near the `_ => "other"` arm)

I won't add to those; @WareWolf already explained them well and they're optional.

---

### 🔵 [suggestion] `docs/book/src/channels/acp.md` doesn't reflect the new payload shape

The ACP doc at `docs/book/src/channels/acp.md:55-72` shows example `session/update` payloads with `kind: tool_call` and `kind: tool_result`. This PR adds a stable `id` field on both for correlation and replaces the substring-heuristic `tool_kind` with a fixed mapping (`read` / `edit` / `delete` / `execute` / `fetch` / `search` / `think` / `other`). The agent-client-protocol spec at https://agentclientprotocol.com/ is the authoritative wire reference, so the omission isn't a contract issue. A one-paragraph note in the "Streaming events" section explaining the correlation `id` and the deterministic kind mapping would save ACP-client authors a round-trip into the source. Optional, take it in a follow-up rather than blocking on it. The `zeroclaw-api` docblock additions on `TurnEvent::ToolCall.id` and `TurnEvent::ToolResult.id` already cover the in-tree consumer side.

---

### Other clippy fixups in 717d0d31 / 990125b34

Skimmed the rest:

- `sort_by(|a, b| b.X.cmp(&a.X))` → `sort_by_key(|x| std::cmp::Reverse(x.X))`. All call sites use Copy types (usize, enum priorities). Equivalent. 🟢
- `loop { let Some(_) = ... else { break; }; ... }` → `while let Some(_) = ... { ... }`. Equivalent. 🟢
- `into_iter().chain(secondary_url.into_iter())` → `.chain(secondary_url)`. `secondary_url` already implements `IntoIterator`. Equivalent. 🟢
- `_temperature: f64` → `_temperature: Option<f64>` in `agent.rs` test mocks: catches up with the master-side trait change. 🟢
- `rppal` moved into `[target.'cfg(target_os = "linux")'.dependencies]`: correct, `rppal` is a Raspberry Pi GPIO crate that doesn't build on macOS. 🟢

Aside from policy.rs, the clippy churn looks mechanical and safe.

---

### Conflict status

Mergeable per gh, but the conflict note from @Audacity88 stands: this PR and #5705 both touch `TurnEvent`, `agent.rs`, and `ws.rs`. Whoever merges second adds the other's enum field. Mechanical, not a review block.

---

Once policy.rs:551 is restored to the consumption form and `command_injection_and_chain_blocked` passes again, this is good to go.

**Comment by tidux** [comment]
@singlerider fixed.

**Review by singlerider — APPROVED** [review]
## Re-review at ef92096c

### 🔴 [resolved] RESOLVED ✅ — `&&` chain parsing restored

ef92096c4 puts `next_if_eq(&'&')` back into the guard with an explanatory comment:

```rust
// This must consume the second '&' so `&&` is not later
// re-read as a lone trailing '&'.
'&' if chars.next_if_eq(&'&').is_none() => {
    return true;
}
```

Side-effect-in-guard is unusual for Rust style, but it's the right shape for this specific case: the pattern `'&'` matches a single arm in this match, so the guard fires exactly once per `&` encounter, and the consumption is part of the recognition. The comment captures the intent explicitly so the next reader (or another pass of clippy) doesn't try to "fix" it again.

I verified by checking out ef92096c and running the test suite for that file:

```
test policy::tests::command_injection_and_chain_blocked ... ok
test result: ok. 154 passed; 0 failed; 0 ignored
```

The companion test `quoted_ampersand_and_redirect_literals_are_not_treated_as_operators` also passes, so quoted-`&` literals stay safe.

### Other prior items

@Audacity88's CHANGES_REQUESTED items (parallel correlation, `map_tool_kind`, content duplication, plan doc, breaking-change docs) all confirmed RESOLVED ✅ at the prior re-review and stay resolved.

@WareWolf-MoonWall's three 🔵 notes (`unwrap()` fragility, FIFO-per-name limit comment, `map_tool_kind` drift comment) and my 🔵 on `docs/book/src/channels/acp.md` are unchanged — all explicitly non-blocking, fine to take in follow-ups.

### Conflict status

Mergeable per gh, but the conflict note from @Audacity88 stands: this PR and #5705 both touch `TurnEvent`, `agent.rs`, and `ws.rs`. Whoever lands second adds the other's enum field. Mechanical, not a review block.

LGTM — approving.

**Comment by warewolf** [comment]
> I won't add to those; @warewolf already explained them well and they're optional.

tagged the wrong warewolf. 👋
